# Generated by Django 2.2 on 2020-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_auto_20200625_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ejemplar',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ejemplares',
            field=models.ManyToManyField(to='biblioteca.Ejemplar'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='localizacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
